-- V2: Add matricula (auto-generated unique identifier) and departamento fields to users table.
-- matricula format: ICF<yyyy><5 digits> (e.g. ICF202600001), generated by UserService/AdminSeeder.
-- departamento is optional free-text (department/area the user belongs to).

ALTER TABLE users
    ADD COLUMN matricula   VARCHAR(20)  NOT NULL DEFAULT '' COMMENT 'Auto-generated unique academic ID (e.g. ICF202600001)',
    ADD COLUMN departamento VARCHAR(100) NULL     COMMENT 'Department or area the user belongs to';

-- Ensure matricula is unique (non-empty values are set by application logic before insert).
ALTER TABLE users
    ADD UNIQUE KEY uk_users_matricula (matricula);
